### ISSUE TITLE
Rhapsodies of Vanadiel songs

### ISSUE THREAD

**Issue by Turbero** [svanheulen/setbgm-windower-addon#2]
Could you introduce the new songs that came along with Rhapsodies of Vanadiel? They cannot be set unless you add to the songs' list in the addon (I did manually in my computer and they can be played).

79: Reisenjima's theme
80: Escha's theme
81: August's theme
82: Cloud of Darkness fight theme
83: End credits theme

Regards and thanks for replacing the former vanatunes plugin!

**Comment by svanheulen** [comment]
Thanks, I added those and submitted it to the official Windower repo.
